DROP SEQUENCE TRACE_LOG_SEQ;

CREATE SEQUENCE TRACE_LOG_SEQ;

DROP TABLE TRACE_LOG;

CREATE TABLE TRACE_LOG
(
    ID NUMBER,
    TS TIMESTAMP,
    TY CHAR(1),
	CALLER VARCHAR2(255),
    MSG VARCHAR2(4000),
    MSGL CLOB, 
    MODULE VARCHAR2(32) DEFAULT SYS_CONTEXT('USERENV', 'MODULE'),
    ACTION VARCHAR2(32) DEFAULT SYS_CONTEXT('USERENV', 'ACTION'),      
    SID VARCHAR2(32) DEFAULT SYS_CONTEXT('USERENV', 'SID'),
    CURRENT_USER VARCHAR2(32) DEFAULT SYS_CONTEXT('USERENV', 'CURRENT_USER'),
    OS_USER VARCHAR2(32) DEFAULT SYS_CONTEXT('USERENV', 'OS_USER'),  
    HOST VARCHAR2(32) DEFAULT SYS_CONTEXT('USERENV', 'HOST'),
    IP_ADDRESS VARCHAR2(32) DEFAULT SYS_CONTEXT('USERENV', 'IP_ADDRESS')
);

QUIT
